`timescale 1ns / 1ps

/*
 * -----------------------------------------------------------------------------
 * Module Name:  instruction_memory
 * Project:      RISC V 32bit Processor
 * Date:         2026-03-05
 * * Description:
 * Implements the Instruction Memory (ROM) for the processor's frontend. It acts 
 * as the primary storage for the compiled machine code, outputting the 32-bit 
 * instruction corresponding to the provided Program Counter (PC). The memory 
 * is modeled with asynchronous (combinational) read access to fulfill the 
 * timing requirements of the Instruction Fetch (IF) stage.
 * * Inputs:
 * - read_address: 32-bit address generated by the Program Counter (PC).
 * * Outputs:
 * - instruction:  32-bit fetched machine instruction word.
 * -----------------------------------------------------------------------------
 */
module instruction_memory(
    input  wire [31:0] read_address,
    output wire [31:0] instruction
);

    // Architectural Note: Storage Allocation
    // The memory array is instantiated as 16,384 discrete 32-bit words. 
    // This provides a total instruction storage footprint of 64 Kilobytes (KB).
    reg [31:0] memory [0:16383];

    // Implementation Detail: Firmware Initialization
    // The $readmemh system task is utilized to preload the memory array with 
    // hexadecimal machine code from an external firmware file ("code.mem") 
    // during the initial simulation or FPGA configuration phase.
    initial begin
        $readmemh("code.mem", memory);
    end

    // Design Consideration: Byte-to-Word Address Translation
    // The base RISC-V ISA mandates byte-addressed memory, necessitating that 
    // the PC increments by 4 for sequential 32-bit instructions. However, the 
    // physical register array is indexed by word. Extracting bits [15:2] of 
    // the read_address performs an implicit integer division by 4, mapping the 
    // byte-aligned PC to the correct word-aligned array index.
    assign instruction = memory[read_address[15:2]];

endmodule
